package com.glaucus;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/*
 * @see #@SpringBootApplication this tells the application is a spring boot application.
 * Auto generated by spring stater web app.
 */
@SpringBootApplication
public class GlaucusInterviewNumberIncrementApplication {

	// below is the entry point to start  a Spring application.
	public static void main(String[] args) {
		SpringApplication.run(GlaucusInterviewNumberIncrementApplication.class, args);
	}

}
